# build a new hadoop image with basic centos
FROM centos
# who is the author
MAINTAINER alex <362615233@qq.com>


# install some important softwares
RUN yum -y install openssh-server openssh-clients net-tools which

############### Configurate JDK #################
# make a new directory to store the jdk files
RUN mkdir -p /soft/

# copy the jdk archive to the image, and it will automaticlly unzip the tar file
ADD jdk-8u101-linux-x64.tar.gz /soft/

# make a symbol link
RUN ln -s /soft/jdk1.8.0_101/ /soft/jdk

############## Configurate SSH #################
# generate ssh key files
RUN ssh-keygen -q -t rsa -b 2048 -f /etc/ssh/ssh_host_rsa_key -N ''
RUN ssh-keygen -q -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N ''
RUN ssh-keygen -q -t dsa -f /etc/ssh/ssh_host_ed25519_key -N ''

# login localhost without password
RUN ssh-keygen -f /root/.ssh/id_rsa -N ''
RUN cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys


############## Configurate Hadoop #################
# copy the hadoop archive to the image, and it will automaticlly unzip the tar file
ADD hadoop-2.7.5.tar.gz /soft/

# make a symbol link
RUN ln -s /soft/hadoop-2.7.5/ /soft/hadoop

# copy the configuration file to image
#COPY core-site.xml /soft/hadoop/etc/hadoop/
#COPY hdfs-site.xml /soft/hadoop/etc/hadoop/

# change hadoop environment variables
RUN sed -i "s?JAVA_HOME=\${JAVA_HOME}?JAVA_HOME=/soft/jdk?g" /soft/hadoop/etc/hadoop/hadoop-env.sh


############## Integration configuration #################
# set environment variables
ENV JAVA_HOME /soft/jdk
ENV JRE_HOME ${JAVA_HOME}/jre
ENV CLASSPATH .:${JAVA_HOME}/lib;${JRE_HOME}/lib
ENV HADOOP_HOME /soft/hadoop
ENV PATH ${HADOOP_HOME}/bin:${HADOOP_HOME}/sbin:${JAVA_HOME}/bin:$PATH

# set password of root
RUN echo "root:" | chpasswd

# when start a container it will be executed
CMD ["/usr/sbin/sshd"]
